fetherstill/urls.py
# project_name/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
# urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'myapp'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home_view, name="home"),
    path('upload/', views.upload_view, name="upload"),
    path('data/<str:data_section>/', views.common_section, name='common_section'),
    path('csv_export/<str:data_section>/', views.export_to_csv, name='csv_export'),
    path('excel_export/<str:data_section>/', views.export_to_excel, name='excel_export'),
    path('json_export/<str:data_section>/', views.export_to_json, name='json_export'),

    # path('battery/', views.battery_view, name='battery'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myapp/forms.py
# forms.py
from django import forms
from datetime import datetime




class DataFilterForm(forms.Form):
    # start_date = forms.DateField(label='Start Date')
    # end_date = forms.DateField(label='End Date')
    start_iteration = forms.IntegerField(label='Start Iteration')
    end_iteration = forms.IntegerField(label='End Iteration')


class IterationFilterForm(forms.Form):
    min_iteration = forms.IntegerField(label="Min Iteration", required=False)
    max_iteration = forms.IntegerField(label="Max Iteration", required=False)
class CpuTimeFilterForm(forms.Form):
    min_cputime = forms.IntegerField(label="Min cputime", required=False)
    max_cputime = forms.IntegerField(label="Max cputime", required=False)
class TravelsFilterForm(forms.Form):
    min_travels = forms.DecimalField(label="Min travels", required=False)
    max_travels = forms.DecimalField(label="Max travels", required=False)
class ValueFilterForm(forms.Form):
    min_value = forms.DecimalField(label="Min value", required=False)
    max_value = forms.DecimalField(label="Max value", required=False)

# Pump filters

class WattsFilterForm(forms.Form):
    min_w = forms.DecimalField(label="Min watt", required=False)
    max_w = forms.DecimalField(label="Max watt", required=False)
class VoltsFilterForm(forms.Form):
    min_v = forms.DecimalField(label="Min voltage", required=False)
    max_v = forms.DecimalField(label="Max voltage", required=False)
class AmperesFilterForm(forms.Form):
    min_a = forms.DecimalField(label="Min ampere", required=False)
    max_a = forms.DecimalField(label="Max ampere", required=False)
class FlowFilterForm(forms.Form):
    min_flow = forms.DecimalField(label="Min flow", required=False)
    max_flow = forms.DecimalField(label="Max flow", required=False)
class TempFilterForm(forms.Form):
    min_temp = forms.DecimalField(label="Min temperature", required=False)
    max_temp = forms.DecimalField(label="Max temperature", required=False)
class RateFilterForm(forms.Form):
    min_rate = forms.DecimalField(label="Min rate", required=False)
    max_rate = forms.DecimalField(label="Max rate", required=False)

class DateFilterForm(forms.Form):
    date_format = '%b. %d, %Y, %I:%M %p'

    min_date = forms.CharField(
        required=False,
        widget=forms.TextInput(),
    )
    max_date = forms.CharField(
        required=False,
        widget=forms.TextInput(),
    )

    def clean_min_date(self):
        min_date_str = self.cleaned_data.get('min_date')
        if min_date_str:
            return datetime.strptime(min_date_str, self.date_format)
        return None

    def clean_max_date(self):
        max_date_str = self.cleaned_data.get('max_date')
        if max_date_str:
            return datetime.strptime(max_date_str, self.date_format)
        return None

myapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.files.storage import FileSystemStorage
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings
import os
from datetime import datetime as dt

from .models import Pump, Inflow, Outflow, UploadLog
from .forms import *
import pandas as pd
from myapp.databaseIngest import ingest


def is_admin_or_staff(user):
    return user.is_superuser

def is_atleast_staff(user):
    return user.is_staff

@login_required(login_url="myapp:login_view")
@user_passes_test(is_atleast_staff)
def common_section(request, data_section):
    date_format = '%b. %d, %Y, %I:%M %p'

    if data_section == 'pump':
        data = Pump.objects.all()

        watts_form = WattsFilterForm(request.GET)
        volts_form = VoltsFilterForm(request.GET)
        amp_form = AmperesFilterForm(request.GET)
        flow_form = FlowFilterForm(request.GET)
        temp_form = TempFilterForm(request.GET)
        rate_form = RateFilterForm(request.GET)
        date_form = DateFilterForm(request.GET)

        # Process and apply the filters based on the form data

        filtered_data = data

        if watts_form.is_valid():
            min_w = watts_form.cleaned_data.get('min_w')
            max_w = watts_form.cleaned_data.get('max_w')
            print(min_w)
            if min_w is not None:
                filtered_data = filtered_data.filter(w__gte=min_w)
            if max_w is not None:
                filtered_data = filtered_data.filter(w__lte=max_w)
        if volts_form.is_valid():
            min_v = volts_form.cleaned_data.get('min_v')
            max_v = volts_form.cleaned_data.get('max_v')
            if min_v is not None:
                filtered_data = filtered_data.filter(v__gte=min_v)
            if max_v is not None:
                filtered_data = filtered_data.filter(v__lte=max_v)
        if amp_form.is_valid():
            min_a = amp_form.cleaned_data.get('min_a')
            max_a = amp_form.cleaned_data.get('max_a')
            if min_a is not None:
                filtered_data = filtered_data.filter(a__gte=min_a)
            if max_a is not None:
                filtered_data = filtered_data.filter(a__lte=max_a)
        if flow_form.is_valid():
            min_flow = flow_form.cleaned_data.get('min_flow')
            max_flow = flow_form.cleaned_data.get('max_flow')
            if min_flow is not None:
                filtered_data = filtered_data.filter(flow_l_min__gte=min_flow)
            if max_flow is not None:
                filtered_data = filtered_data.filter(flow_l_min__lte=max_flow)
        if temp_form.is_valid():
            min_temp = temp_form.cleaned_data.get('min_temp')
            max_temp = temp_form.cleaned_data.get('max_temp')
            if min_temp is not None:
                filtered_data = filtered_data.filter(temp_field__gte=min_temp)
            if max_temp is not None:
                filtered_data = filtered_data.filter(temp_field__lte=max_temp)
        if rate_form.is_valid():
            min_rate = rate_form.cleaned_data.get('min_rate')
            max_rate = rate_form.cleaned_data.get('max_rate')
            if min_rate is not None:
                filtered_data = filtered_data.filter(r_sec__gte=min_rate)
            if max_rate is not None:
                filtered_data = filtered_data.filter(r_sec__lte=max_rate)
        if date_form.is_valid():
            min_date = date_form.cleaned_data.get('min_date')
            max_date = date_form.cleaned_data.get('max_date')
            if min_date is not None:
                filtered_data = filtered_data.filter(datetime__gte=min_date)
            if max_date is not None:
                filtered_data = filtered_data.filter(datetime__lte=max_date)

        sort_by = request.GET.get('sort_by', 'w')  # Default to 'iteration' if no column is specified
        sort_order = request.GET.get('sort_order', 'asc')  # Sort order: 'asc' or 'desc'

        order_field = sort_by
        if sort_order == 'desc':
            order_field = '-' + order_field

        # Apply sorting to the filtered data
        sorted_data = filtered_data.order_by(order_field)

        items_per_page = 15

        paginator = Paginator(sorted_data, items_per_page)
        page = request.GET.get('page')

        try:
            pagi_data = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            pagi_data = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g., 9999), deliver last page.
            pagi_data = paginator.page(paginator.num_pages)

        return render(request, 'section.html', {
            'data': pagi_data,
            'watts_form': watts_form,
            'volts_form': volts_form,
            'amp_form': amp_form,
            'flow_form': flow_form,
            'temp_form': temp_form,
            'rate_form': rate_form,
            'date_form': date_form,
            'data_section': data_section,
        })
    
    else:
        iteration_form = IterationFilterForm(request.GET)
        cpu_time_form = CpuTimeFilterForm(request.GET)
        travels_form = TravelsFilterForm(request.GET)
        value_form = ValueFilterForm(request.GET)

        # Process and apply the filters based on the form data
        if data_section == 'inlet':
            data = Inflow.objects.all()
        elif data_section == 'outlet':
            data = Outflow.objects.all()

        if iteration_form.is_valid():
            min_iteration = iteration_form.cleaned_data.get('min_iteration')
            max_iteration = iteration_form.cleaned_data.get('max_iteration')
            if min_iteration is not None:
                data = data.filter(iteration__gte=min_iteration)
            if max_iteration is not None:
                data = data.filter(iteration__lte=max_iteration)

        if cpu_time_form.is_valid():
            min_cputime = cpu_time_form.cleaned_data.get('min_cputime')
            max_cputime = cpu_time_form.cleaned_data.get('max_cputime')
            if min_cputime is not None:
                data = data.filter(cputime__gte=min_cputime)
            if max_cputime is not None:
                data = data.filter(cputime__lte=max_cputime)

        if travels_form.is_valid():
            min_travels = travels_form.cleaned_data.get('min_travels')
            max_travels = travels_form.cleaned_data.get('max_travels')
            if min_travels is not None:
                data = data.filter(travels__gte=min_travels)
            if max_travels is not None:
                data = data.filter(travels__lte=max_travels)

        if value_form.is_valid():
            min_value = value_form.cleaned_data.get('min_value')
            max_value = value_form.cleaned_data.get('max_value')
            if min_value is not None:
                data = data.filter(value__gte=min_value)
            if max_value is not None:
                data = data.filter(value__lte=max_value)

        # Sorting logic
        sort_by = request.GET.get('sort_by', 'iteration')  # Default to 'iteration' if no column is specified
        sort_order = request.GET.get('sort_order', 'asc')  # Sort order: 'asc' or 'desc'

        order_field = sort_by
        if sort_order == 'desc':
            order_field = '-' + order_field


        # Apply sorting to the filtered data
        sorted_data = data.order_by(order_field)

        items_per_page = 15

        paginator = Paginator(sorted_data, items_per_page)
        page = request.GET.get('page')

        try:
            pagi_data = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            pagi_data = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g., 9999), deliver last page.
            pagi_data = paginator.page(paginator.num_pages)

        return render(request, 'section.html', {
            'data': pagi_data,  # Pass sorted data to the template
            'iteration_form': iteration_form,
            'cpu_time_form': cpu_time_form,
            'travels_form': travels_form,
            'value_form': value_form,
            'data_section': data_section,
            'sort_order':sort_order
        })


def export_to_csv(request, data_section):
    if data_section == 'pump':
        print("in pump")
        print(data_section)
        data = get_filtered_data(request, data_section)
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="exported_data.csv"'

        # Convert QuerySet to DataFrame
        df = pd.DataFrame(data.values())

        # Select specific columns
        columns = ['w', 'v', 'a', 'flow_l_min', 'r_sec', 'temp_field', 'datetime']
        df = df[columns]

        # Write DataFrame to CSV
        df.to_csv(response, index=False)

    else:
        data = get_filtered_data(request, data_section)
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="exported_data.csv"'

        # Convert QuerySet to DataFrame
        df = pd.DataFrame(data.values())

        # Select specific columns
        columns = ['iteration', 'cputime', 'travels', 'value']
        df = df[columns]

        # Write DataFrame to CSV
        df.to_csv(response, index=False)

    return response


def export_to_excel(request, data_section):

    if data_section == 'pump':
        data = get_filtered_data(request, data_section)
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

myapp/templates/base.html
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'myapp/css/bootstrap.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'myapp/authentication/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/authentication/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/authentication/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/authentication/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/authentication/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/authentication/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/authentication/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/authentication/css/main.css' %}">
<!--===============================================================================================-->

    <title>Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/home.css' %}">

    <style>
        body {
            background-color: #f3f3f3;
        }
        /* Sidebar Styles */
        #sidebar {
            background-color: #375b83;
            color: #ffffff;
            padding: 20px;
        }

        .nav-link {
            color: #ffffff;
            font-size: 16px;
        }

        #sidebar .nav-link ul {
            list-style: none !important;
            padding: 0;
            margin: 0;
        }

        .nav-link:hover {
            background-color: #5eadba;
        }

        .side:link {
          color: #ffffff;
        }
        .side:hover {
          color: #ffffff;
        }


        /* Custom class for the "Battery" heading */
        .battery-heading, .upload-heading {
            font-size: 20px;
        }
        .logout-heading {
            font-size: 15px;
        }

        /* Collapse arrow color */
    [data-bs-toggle="collapse"]::after {
        font-family: 'FontAwesome';
        content: "\f105"; /* fa-chevron-right icon */
        float: right;
        margin-right: 10px;
        transition: transform 0.3s ease; /* Add smooth transition effect */
    }

    [data-bs-toggle="collapse"][aria-expanded="true"]::after {
        transform: rotate(90deg);
    }
    </style>
    {% load static %}
</head>

<body>
    <div class="form .aligned div.help">
        <div class="row h-100">
            <!-- Sidebar (Non-collapsible) -->
            <nav id="sidebar" class="col-md-2">
                <div class="position-sticky">
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <img src="{% static 'myapp/assets/test.png' %}" width="100" height="110" class="d-inline-block align-items-center mb-4" alt="">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                        <a class="nav-link battery-heading side" href="#" data-bs-toggle="collapse" data-bs-target="#batterySubmenu" aria-expanded="false">
                            Battery Module
{#                            <i id="battery-icon" class="fas fa-chevron-right"></i>#}
                        </a>
                            <ul class="nav flex-column collapse" id="batterySubmenu">
                                <li class="nav-item">
                                    <a class="nav-link side" href="{% url 'myapp:common_section' data_section='inlet' %}">
                                        Inlet
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link side" href="{% url 'myapp:common_section' data_section='outlet' %}">
                                        Outlet
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link side" href="{% url 'myapp:common_section' data_section='pump' %}">
                                        Pump
                                    </a>
                                </li>
                            </ul>
                        </li>
                        {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link upload-heading side" href="{% url 'myapp:upload' %}">Upload</a>
                        </li>
                        {% endif %}
                    </ul>

            <li class="nav-item mt-auto">
                <a class="nav-link logout-heading side" href="{% url 'myapp:logout' %}">Logout</a>
            </li>
        </ul>

                </div>
            </nav>

            <!-- Content Area -->
            <div class="col-md-9">
                <div class="container mt-4">
                    <div id="section-content">
                        {% block content %}
                            <!-- Content for the selected section will be included here. -->
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- Bootstrap 5 and jQuery Scripts... -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

    {% block extra_js %}{% endblock extra_js %}
</body>
</html>

myapp/templates/battery.html
{% load static %}

<link
rel = "stylesheet"
type = "text/css"
href = "{%  static 'myapp/css/bootstrap.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fetherstill</title>
    <!-- Add Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="#">Fetherstill</a>
            <div class="navbar-nav ml-auto">
                <a class="nav-item nav-link" href="#"><i class="bi bi-gear"></i> Settings</a>
                <a class="nav-item nav-link" href="#"><i class="bi bi-person"></i> Profile</a>
            </div>
        </div>
    </nav>

    <!-- Content Area -->
    <div class="container mt-4">
        <!-- Dashboard Table -->
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Battery ID</th>
                    <th scope="col">Temperature</th>
{#                    <th scope="col">Pressure</th>#}
                    <th scope="col">Timestamp</th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                <tr>
                    <td>{{ item.battery_number }}</td>
                    <td>{{ item.temperature }}</td>
                    <td>{{ item.voltage }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Bootstrap 5 and jQuery Scripts -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/home.html
{% extends "base.html" %}
{% block content  %}
    {% load static %}
    <div class="fether-container" >
    <!-- Your actual content goes here -->
    <img class="content-image" src="{% static 'myapp/assets/test.png' %}" alt="Your Image Description">
</div>

{% endblock %}

myapp/templates/section.html
{% extends "base.html" %}

{% block content %}
        {% if data_section == 'inlet' %}
        {% include "inlet_data.html" %}
    {% elif data_section == 'outlet' %}
        {% include "outlet_data.html" %}
    {% elif data_section == 'pump' %}
        {% include "pump_data.html" %}
    {% endif %}


{#    <style>#}
{#        table {#}
{#            width: 100%;#}
{#            border-collapse: collapse;#}
{#        }#}
{##}
{#        th, td {#}
{#            padding: 10px;#}
{#            border: 1px solid #ddd;#}
{#        }#}
{##}
{#        th {#}
{#            background-color: #f2f2f2;#}
{#        }#}
{##}
{#        tr:hover {#}
{#            background-color: #f5f5f5;#}
{#        }#}
{#    </style>#}

    <!-- Filter form -->
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <input type="submit" value="Filter Data">#}
{#    </form>#}

{#    <table>#}
{#        <thead>#}
{#            <tr>#}
{#                <th>#}
{#                    {% if request.GET.sort_order == "asc" %}#}
{#                        <a href="?sort_by=iteration&sort_order=desc">Iterations ↓</a>#}
{#                    {% else %}#}
{#                        <a href="?sort_by=iteration&sort_order=asc">Iterations ↑</a>#}
{#                    {% endif %}#}
{#                </th>#}
{#                <!-- Add similar blocks for other columns -->#}
{#                <th>#}
{#                    {% if request.GET.sort_order == "asc" %}#}
{#                        <a href="?sort_by=cputime&sort_order=desc">CPU Time ↓</a>#}
{#                    {% else %}#}
{#                        <a href="?sort_by=cputime&sort_order=asc">CPU Time ↑</a>#}
{#                    {% endif %}#}
{#                </th>#}
{#                <th>#}
{#                    {% if request.GET.sort_order == "asc" %}#}
{#                        <a href="?sort_by=travels&sort_order=desc">Travels ↓</a>#}
{#                    {% else %}#}
{#                        <a href="?sort_by=travels&sort_order=asc">Travels ↑</a>#}
{#                    {% endif %}#}
{#                </th>#}
{#                <th>#}
{#                    {% if request.GET.sort_order == "asc" %}#}
{#                        <a href="?sort_by=value&sort_order=desc">Value ↓</a>#}
{#                    {% else %}#}
{#                        <a href="?sort_by=value&sort_order=asc">Value ↑</a>#}
{#                    {% endif %}#}
{#                </th>#}
{#            </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#            {% for item in data %}#}
{#                <tr>#}
{#                    <td>{{ item.iteration }}</td>#}
{#                    <td>{{ item.cputime }}</td>#}
{#                    <td>{{ item.travels }}</td>#}
{#                    <td>{{ item.value }}</td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#        </tbody>#}
{#    </table>#}
{% endblock %}

myapp/templates/upload.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
    <style>

    </style>
</head>
    <body>
            {% block content %}
            <div class="container">
                <h2 class="fw-bold">File Upload</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="file-category">Category:</label>
                                <select class="form-control" id="file-category" name="file-category" required>
                                    <option value="" disabled selected>Select Category</option>
                                </select>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="file-type">File Type:</label>
                                <select class="form-control" id="file-type" name="file-type" required>
                                    <option value="" disabled selected>Select Type</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="file-date">File Date:</label>
                                <input type="date" class="form-control" id="file-date" name="file-date" required>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="file">Choose File:</label>
                        <input type="file" class="form-control-file" id="file" name="file" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
                {% if name %}
                    <p>{{ name }} uploded successfully!</p>
                {% endif %}
            {% endblock content %}
        </div>

        {% block extra_js %}
        <script>
            var categoryObject = {
                "Battery Module": ["Inlet", "Outlet", "Pump"],
                "Simulation": ["Type 1", "Type 2"]
            }
            window.onload = function() {
                var categorySel = document.getElementById("file-category");
                var typeSel = document.getElementById("file-type");
                for (var x in categoryObject) {
                    categorySel.options[categorySel.options.length] = new Option(x, x);
                }
                categorySel.onchange = function() {
                    //empty Type- dropdown
                    typeSel.length = 1;
                    //display correct values
                    var y = categoryObject[this.value]
                    for (var i = 0; i < y.length; i++) {
                        typeSel.options[typeSel.options.length] = new Option(y[i], y[i])
                    }
                }
            }
        </script>
        {% endblock extra_js %}
    </body>
</html>